language: android

android:
  components:
    - tools
    - platform-tools                    # Platform tools
    - build-tools-27.0.2
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
licenses:
    - 'android-sdk-license-.+'

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo d56f5187479451eabf01fb78af6dfcb131a6481e > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo 24333f8a63b6825ea9c5514f83c2829b004d1fee >> "$ANDROID_HOME/licenses/android-sdk-license"

jdk:
  - oraclejdk8

script:
  - ./gradlew build

env:
  global:
    - secure: "SONATYPE_NEXUS_USERNAME TODO"
    - secure: "SONATYPE_NEXUS_PASSWORD TODO"

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
