name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        run: ./gradlew help --stacktrace
      - name: Build project
        run: ./gradlew build --stacktrace
      - name: Upload test and lint reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ./rx-central-ble/build/reports
